import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientProvider from '@/graphql/ClientProvider';
import Navbar from './components/Navbar';
import { ThemeProvider } from './context/ThemeContext';
import ClientThemeWrapper from './context/ClientThemeWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Wildrent',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className={inter.className}>
          <ThemeProvider>
            <ClientThemeWrapper>
              <div className="mx-auto max-w-5xl mb-10">
                <Navbar />
                {children}
              </div>
            </ClientThemeWrapper>
          </ThemeProvider>
        </body>
      </ClientProvider>
    </html>
  );
}
