version: '3.8'

services:
  db:
    container_name: postgres
    stop_grace_period: 0s
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  backend:
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    build: backend
    ports:
      - 4001:4001
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./global.env

  frontend:
    stop_grace_period: 0s
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
