version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    depends_on:
      db:
        condition: service_healthy

    build: backend
    ports:
      - 4001:4001
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
