services:
  db:
    image: postgres:15-alpine
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-postgres}
      PGUSER: ${DB_USER-postgres}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - stagingDB:/var/lib/postgresql/data

  backend:
    environment:
      DB_HOST: db
      DB_PASS: ${DB_PASS-postgres}
      DB_USER: ${DB_USER-postgres}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-changeme}
      NODE_ENV: ${NODE_ENV:-production}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-changeme}
    stop_grace_period: 0s
    depends_on:
      db:
        condition: service_healthy
    image: mariontassy/2023-09-wns-bleu-wildrent-server:staging

  frontend:
    stop_grace_period: 0s
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-changeme}
    image: mariontassy/2023-09-wns-bleu-wildrent-client:staging

  gateway:
    stop_grace_period: 0s
    restart: always
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT-80}:80
    volumes: 
      - .log:/var/log/nginx

volumes:
  stagingDB:
