FROM node:20.9.0-alpine3.17

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY ./tsconfig.json ./tsconfig.json
COPY ./src ./src
COPY ./jest.config.ts ./jest.config.ts
COPY ./jest.setup.ts ./jest.setup.ts

RUN npm run build

CMD npm run start:prod
