import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import SelectDate from '../components/SelectDate';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Wildrent',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  return (
    <div className="flex flex-col min-h-screen">
      <div className="mx-auto max-w-5xl w-full flex-grow">
        <Navbar />
        {router.pathname !== '/about' && <SelectDate />}
        <div className="container mx-auto px-4 min-h-full">{children}</div>
      </div>
      <Footer />
    </div>
  );
}
