query GetProductAvailableByDateRange($endDate: String, $startDate: String) {
  getProductAvailableByDateRange(endDate: $endDate, startDate: $startDate) {
    items {
      id
      name
      description
      image
      priceHT
      quantityAvailable
    }
  }
}
