query AllProductRefs($name: String, $endDate: String, $startDate: String) {
  allProductRefs(name: $name, endDate: $endDate, startDate: $startDate) {
    id
    name
    image
    priceHT
    quantityAvailable
  }
}

query AllProductRefsAdmin {
  allProductRefs {
    id
    name
    description
    image
    priceHT
    subCategory {
      name
      category {
        name
      }
    }
    quantityAvailable
  }
}
