query AllProductRefs {
  allProductRefs {
    id
    name
    image
    priceHT
  }
}

query AllProductRefsAdmin {
  allProductRefs {
    id
    name
    description
    image
    priceHT
    subCategory {
      name
      category {
        name
      }
    }
    quantity
    quantityAvailable
  }
}
