query ProductRefById($productRefId: Int!, $endDate: String, $startDate: String) {
  productRefById(productRefId: $productRefId, endDate: $endDate, startDate: $startDate) {
    id
    name
    description
    image
    priceHT
    quantity
    quantityAvailable
    subCategory {
      id
      name
      category {
        id
        name
      }
    }
  }
}
