name: Test, compile and push client and server to production

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  client-tests:
    uses: WildCodeSchool/2023-09-wns-bleu-wildrent/.github/workflows/tests-frontend.yml@dev
  e2e-tests:
    uses: WildCodeSchool/2023-09-wns-bleu-wildrent/.github/workflows/e2e-tests.yml@dev

  integration-tests:
    uses: WildCodeSchool/2023-09-wns-bleu-wildrent/.github/workflows/integration-tests.yml@dev

  build-and-push-server:
    needs:
      - integration-tests
      - e2e-tests
    uses: WildCodeSchool/2023-09-wns-bleu-wildrent/.github/workflows/build-backend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: mariontassy/2023-09-wns-bleu-wildrent-server:staging

  build-and-push-client:
    needs:
      - client-tests
      - e2e-tests
    uses: WildCodeSchool/2023-09-wns-bleu-wildrent/.github/workflows/build-frontend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: mariontassy/2023-09-wns-bleu-wildrent-client:staging

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.0923-bleu-4.wns.wilders.dev/hooks/update-staging
